title: Sanskar R. # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Developer Intern
  <br><br>
  <a href="mailto:sanskarram992@gmail.com">sanskarram992@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/sanskar-r-402140179/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/sanskarram981/">Gihub</a> 
theme: jekyll-theme-minimal
